# Custom docker image with Kubectl, AWS and Terraform preinstalled
image: kubectl_terraform:latest

variables:
  DOCKER_REPO: ketanstechracers/dockerize-rails
  TFVARS_FILE_PATH: ./deploy_rails_app/terraform.tfvars

before_script:
  # configure AWS CLI
  - aws configure set aws_access_key_id $AWS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET
  - aws configure set region "us-east-1"
  # Point kubectl to our target eks cluster
  - aws eks --region "us-east-1" update-kubeconfig --name demo

stages:
  - test
  - build
  - deploy

Tests:
  stage: test
  script:
    - echo "=== 5/1 RUNNING TESTS ===="
    - bundle exec rails test -d

Build:
  stage: build
  only:
    - master
  script:
    - echo "=== 5/2 BUILDING DOCKER IMAGE ===="
    - COMMIT_SHA="$(git rev-parse HEAD)"
    - COMMIT_MSG="$(git log -1 --pretty=%B)"
    - TAG="$(git describe --abbrev=0 --tags)"
    - docker build . --label "commit_sha=$COMMIT_SHA" --label "commit_msg=$COMMIT_MSG"
    - IMAGE_ID="$(sudo docker images -f label=commit_sha=$COMMIT_SHA | head -n 2 | tail -n 1 | awk '{print $3}')"
    - echo Succesfully built image $IMAGE_ID
    - docker tag $IMAGE_ID $REPO:$TAG
    - echo "=== 5/3 PUSHING DOCKER IMAGE ===="
    - docker push $DOCKER_REPO:$TAG
    - echo "=== 5/4 UPDATING TAGS IN terraform.tfvars FILE ===="
    # Get the contents of terraform.tfvars file and update the `rails_docker_tag` variable
    # to the latest pushed docker tag  
    - echo $TFVARS | base64 -d > $TFVARS_FILE_PATH
    - line_number="$(cat $TFVARS_FILE_PATH | grep -n rails_docker_tag | awk '{print $1}' | sed 's/://')"
    - cmd="${line_number}s/.*/rails_docker_tag = ${TAG}/"
    - sed -i "$cmd" "$TFVARS_FILE_PATH"

Deploy:
  stage: deploy
  retry: 2
  only:
    - master
  script:
    - echo "=== 5/5 DEPLOYING UPDATED RAILS APP ===="
    - make rails-up
